import Link from 'next/link'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#111c2d] text-white">
      {/* Nav */}
      <nav className="flex items-center justify-between px-6 py-4 border-b border-white/5">
        <Link href="/" className="font-heading font-bold text-lg tracking-tight">
          Growth<span className="text-[#6366f1]"> OS</span>
        </Link>
        <Link
          href="/"
          className="text-sm text-white/60 hover:text-white transition-colors"
        >
          Back to Home
        </Link>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="font-heading text-4xl font-bold mb-8">Terms of Service</h1>
        <p className="text-sm text-white/40 mb-10">Last updated: April 9, 2026</p>

        <div className="space-y-8">
          <section className="glass-panel rounded-2xl p-6 space-y-3">
            <h2 className="font-heading font-semibold text-lg">1. Acceptance of Terms</h2>
            <p className="text-sm text-white/60 leading-relaxed">
              By accessing or using Growth OS (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, you may not use the Service. These terms apply to all visitors,
              users, and others who access or use the Service.
            </p>
          </section>

          <section className="glass-panel rounded-2xl p-6 space-y-3">
            <h2 className="font-heading font-semibold text-lg">2. Description of Service</h2>
            <p className="text-sm text-white/60 leading-relaxed">
              Growth OS is an AI-powered marketing platform designed for direct-to-consumer brands.
              The Service provides AI agent-based marketing automation, analytics, content generation,
              and campaign management tools. Features and availability may change without prior notice.
            </p>
          </section>

          <section className="glass-panel rounded-2xl p-6 space-y-3">
            <h2 className="font-heading font-semibold text-lg">3. User Accounts</h2>
            <p className="text-sm text-white/60 leading-relaxed">
              You are responsible for safeguarding your account credentials and for all activities
              that occur under your account. You must notify us immediately of any unauthorized use
              of your account. Growth OS cannot and will not be liable for any loss or damage arising
              from your failure to comply with this requirement.
            </p>
          </section>

          <section className="glass-panel rounded-2xl p-6 space-y-3">
            <h2 className="font-heading font-semibold text-lg">4. Credits and Billing</h2>
            <p className="text-sm text-white/60 leading-relaxed">
              The Service operates on a credit-based system. Credits are consumed when AI agents
              execute skills on your behalf. Unused credits do not roll over between billing periods
              unless otherwise stated in your plan. Refunds are handled on a case-by-case basis.
            </p>
          </section>

          <section className="glass-panel rounded-2xl p-6 space-y-3">
            <h2 className="font-heading font-semibold text-lg">5. Intellectual Property</h2>
            <p className="text-sm text-white/60 leading-relaxed">
              Content generated by AI agents on your behalf is owned by you, subject to the
              underlying model providers&apos; terms. The Growth OS platform, its design, code, and
              branding remain the intellectual property of Growth OS and its licensors.
            </p>
          </section>

          <section className="glass-panel rounded-2xl p-6 space-y-3">
            <h2 className="font-heading font-semibold text-lg">6. Limitation of Liability</h2>
            <p className="text-sm text-white/60 leading-relaxed">
              To the maximum extent permitted by law, Growth OS shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages resulting from your use of the
              Service. AI-generated content should be reviewed before publication or use in business
              decisions.
            </p>
          </section>

          <section className="glass-panel rounded-2xl p-6 space-y-3">
            <h2 className="font-heading font-semibold text-lg">7. Changes to Terms</h2>
            <p className="text-sm text-white/60 leading-relaxed">
              We reserve the right to modify these terms at any time. We will notify users of
              significant changes via email or in-app notification. Continued use of the Service
              after changes constitutes acceptance of the modified terms.
            </p>
          </section>

          <section className="glass-panel rounded-2xl p-6 space-y-3">
            <h2 className="font-heading font-semibold text-lg">8. Contact</h2>
            <p className="text-sm text-white/60 leading-relaxed">
              For questions about these Terms, please contact us at{' '}
              <a href="mailto:legal@growthOS.ai" className="text-[#6366f1] hover:underline">
                legal@growthOS.ai
              </a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
